version: '3'

services:
  frappe:
    image: registry.cn-hangzhou.aliyuncs.com/lvxj11/nexterp:20201118
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=Pass0129
      - ADMIN_PASSWORD=admin
    ports:
      - "46110:80"
      - "46111:443"
      - "46112:8000"
    depends_on:
      - redis
      - mariadb
    links:
      - redis
      - mariadb
    volumes:
      - sites:/home/frappe/frappe-bench/sites:rw
      - nginx:/etc/nginx

  redis:
    image: redis:5
    restart: unless-stopped

  mariadb:
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Pass0129
    ports:
      - "46113:3306"
    volumes:
      - ./frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - data_db:/var/lib/mysql

volumes:
  data_db:
  sites:
  nginx:
